#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SchoolApps.Resource", IsApplication=true)]

namespace SchoolApps
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::SchoolApps.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::SchoolApps.Resource.String.Hello;
			global::Gcm.Client.Resource.String.library_name = global::SchoolApps.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int MenuArrays = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050005
			public const int blackColor = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int cellback = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int gray = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int lowercasecompatiblesabfm = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int schoolAppsBlue = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int schoolAppsBlueBanner = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int schoolAppsBlueForMenu = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int titleBackgroundColor = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int whiteColour = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background_textured_schoolapp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ab_bottom_solid_schoolapp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ab_solid_schoolapp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ab_stacked_solid_schoolapp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ab_texture_tile_schoolapp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ab_transparent_schoolapp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int action_menu = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int action_other = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int action_search = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int BorderLines = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_cab_done_default_schoolapp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btn_cab_done_focused_schoolapp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int btn_cab_done_pressed_schoolapp = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int btn_cab_done_schoolapp = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int cab_background_bottom_schoolapp = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int cab_background_top_schoolapp = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int CustomSelector = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int CustomSelectorForLeftMenu = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int drawer_shadow_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int drawer_shadow_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int facebookDP = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_drawer_dark = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_drawer_light = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_drawer_white = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_launcher = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_list_feedback = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_list_info = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_list_news = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_list_profile = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_list_setting = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Icon = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int list_focused_schoolapp = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int list_pressed_schoolapp = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int Logo_Menu = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int menu_dropdown_panel_schoolapp = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int Menuicon1 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int monoandroidsplash = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int progress_bg_schoolapp = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int progress_horizontal_schoolapp = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int progress_primary_schoolapp = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int progress_secondary_schoolapp = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int schoolapp_logo = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int selectable_background_schoolapp = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int spinner_ab_default_schoolapp = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int spinner_ab_disabled_schoolapp = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int spinner_ab_focused_schoolapp = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int spinner_ab_pressed_schoolapp = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int spinner_background_ab_schoolapp = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int splash = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int tab_indicator_ab_schoolapp = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int tab_selected_focused_schoolapp = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int tab_selected_pressed_schoolapp = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int tab_selected_schoolapp = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int tab_unselected_focused_schoolapp = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int tab_unselected_pressed_schoolapp = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int tab_unselected_schoolapp = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int u12_normal = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int u13_normal = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int u14_normal = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int u20_normal = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int u31_normal = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int u39_normal = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int Woodgrove = 2130837566;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080020
			public const int FeedbackLL = 2131230752;
			
			// aapt resource value: 0x7f08000f
			public const int Image = 2131230735;
			
			// aapt resource value: 0x7f080054
			public const int MMContainer = 2131230804;
			
			// aapt resource value: 0x7f080055
			public const int MainMenuFlyOutContent = 2131230805;
			
			// aapt resource value: 0x7f080058
			public const int MenuButton = 2131230808;
			
			// aapt resource value: 0x7f080071
			public const int SCAContent = 2131230833;
			
			// aapt resource value: 0x7f08002b
			public const int SCAMenu = 2131230763;
			
			// aapt resource value: 0x7f080010
			public const int Text = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int Text1 = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int Text2 = 2131230738;
			
			// aapt resource value: 0x7f08000a
			public const int btnAddAddressCML = 2131230730;
			
			// aapt resource value: 0x7f080006
			public const int btnComposeMsgAddresseeLVOK = 2131230726;
			
			// aapt resource value: 0x7f08003e
			public const int btnLogin = 2131230782;
			
			// aapt resource value: 0x7f080025
			public const int btnOpenFeedbackForm = 2131230757;
			
			// aapt resource value: 0x7f080086
			public const int btnReadMore = 2131230854;
			
			// aapt resource value: 0x7f080088
			public const int btnReadMorePM = 2131230856;
			
			// aapt resource value: 0x7f080050
			public const int btnResetPassSubmit = 2131230800;
			
			// aapt resource value: 0x7f080049
			public const int btnUserRegRegister = 2131230793;
			
			// aapt resource value: 0x7f080003
			public const int cbComposeMsgAddresseeC = 2131230723;
			
			// aapt resource value: 0x7f080052
			public const int content_frame = 2131230802;
			
			// aapt resource value: 0x7f080051
			public const int drawer_layout = 2131230801;
			
			// aapt resource value: 0x7f08000e
			public const int etComposeMsgLayoutContent = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int etComposeMsgLayoutSubject = 2131230733;
			
			// aapt resource value: 0x7f080009
			public const int etComposeMsgLayoutTo = 2131230729;
			
			// aapt resource value: 0x7f08001f
			public const int etFeedbackContent = 2131230751;
			
			// aapt resource value: 0x7f08001e
			public const int etFromEmail = 2131230750;
			
			// aapt resource value: 0x7f08003c
			public const int etLoginEmail = 2131230780;
			
			// aapt resource value: 0x7f08003d
			public const int etLoginPass = 2131230781;
			
			// aapt resource value: 0x7f08004f
			public const int etResetPassConfirmPass = 2131230799;
			
			// aapt resource value: 0x7f08004d
			public const int etResetPassEmail = 2131230797;
			
			// aapt resource value: 0x7f08004e
			public const int etResetPassNewPass = 2131230798;
			
			// aapt resource value: 0x7f08008f
			public const int etSettingsResetPassConfirmPass = 2131230863;
			
			// aapt resource value: 0x7f08008e
			public const int etSettingsResetPassNewPass = 2131230862;
			
			// aapt resource value: 0x7f08001c
			public const int etToEmail = 2131230748;
			
			// aapt resource value: 0x7f080048
			public const int etUserRegConfirmPass = 2131230792;
			
			// aapt resource value: 0x7f080046
			public const int etUserRegEmail = 2131230790;
			
			// aapt resource value: 0x7f080045
			public const int etUserRegICNo = 2131230789;
			
			// aapt resource value: 0x7f080047
			public const int etUserRegPassword = 2131230791;
			
			// aapt resource value: 0x7f080057
			public const int frameLayout1 = 2131230807;
			
			// aapt resource value: 0x7f08002c
			public const int imageView1 = 2131230764;
			
			// aapt resource value: 0x7f08002f
			public const int imageView2 = 2131230767;
			
			// aapt resource value: 0x7f080022
			public const int ivAppImage = 2131230754;
			
			// aapt resource value: 0x7f080017
			public const int ivEventsIcon = 2131230743;
			
			// aapt resource value: 0x7f080073
			public const int ivGeneralInfoIcon = 2131230835;
			
			// aapt resource value: 0x7f080027
			public const int ivIconImage = 2131230759;
			
			// aapt resource value: 0x7f08005b
			public const int ivInfoAppLogo = 2131230811;
			
			// aapt resource value: 0x7f080038
			public const int ivLeftMenuListViewIconImg = 2131230776;
			
			// aapt resource value: 0x7f08006b
			public const int ivMMFOCEventsIcon = 2131230827;
			
			// aapt resource value: 0x7f080065
			public const int ivMMFOCGenInfoIcon = 2131230821;
			
			// aapt resource value: 0x7f080068
			public const int ivMMFOCMessagesIcon = 2131230824;
			
			// aapt resource value: 0x7f080076
			public const int ivMessagesIcon = 2131230838;
			
			// aapt resource value: 0x7f080080
			public const int ivMsgIcon = 2131230848;
			
			// aapt resource value: 0x7f08004b
			public const int ivResetPassAppLogo = 2131230795;
			
			// aapt resource value: 0x7f08003a
			public const int ivSCLogo = 2131230778;
			
			// aapt resource value: 0x7f08008b
			public const int ivSettingsIcon = 2131230859;
			
			// aapt resource value: 0x7f080043
			public const int ivUserRegSchoolAppsLogo = 2131230787;
			
			// aapt resource value: 0x7f080053
			public const int left_drawer = 2131230803;
			
			// aapt resource value: 0x7f080004
			public const int linearLayout1 = 2131230724;
			
			// aapt resource value: 0x7f080037
			public const int llLeftMenuListView = 2131230775;
			
			// aapt resource value: 0x7f080085
			public const int llReadMore = 2131230853;
			
			// aapt resource value: 0x7f080087
			public const int llReadMorePM = 2131230855;
			
			// aapt resource value: 0x7f08004a
			public const int llResetPass = 2131230794;
			
			// aapt resource value: 0x7f080063
			public const int llThreeButtons = 2131230819;
			
			// aapt resource value: 0x7f080042
			public const int llUserReg = 2131230786;
			
			// aapt resource value: 0x7f080005
			public const int lvComposeMsgAddresseeLV = 2131230725;
			
			// aapt resource value: 0x7f080036
			public const int lvLeftMenuListView = 2131230774;
			
			// aapt resource value: 0x7f08007d
			public const int lvListingEventsInfo = 2131230845;
			
			// aapt resource value: 0x7f08007b
			public const int lvListingGenMsg = 2131230843;
			
			// aapt resource value: 0x7f08007c
			public const int lvListingPrivateMsg = 2131230844;
			
			// aapt resource value: 0x7f080070
			public const int lvMMFOCEvents = 2131230832;
			
			// aapt resource value: 0x7f08006e
			public const int lvMMFOCGenInfo = 2131230830;
			
			// aapt resource value: 0x7f08006f
			public const int lvMMFOCMessages = 2131230831;
			
			// aapt resource value: 0x7f08007e
			public const int lvMessagesStandalone = 2131230846;
			
			// aapt resource value: 0x7f08008a
			public const int lvSettingsLayoutStandalone = 2131230858;
			
			// aapt resource value: 0x7f080014
			public const int pbEntranceLoadingIndicator = 2131230740;
			
			// aapt resource value: 0x7f080013
			public const int relativeLayout1 = 2131230739;
			
			// aapt resource value: 0x7f080024
			public const int relativeLayout2 = 2131230756;
			
			// aapt resource value: 0x7f080021
			public const int rlAppImage = 2131230753;
			
			// aapt resource value: 0x7f080016
			public const int rlEventListView = 2131230742;
			
			// aapt resource value: 0x7f080078
			public const int rlEventsBtn = 2131230840;
			
			// aapt resource value: 0x7f080098
			public const int rlGenMsg = 2131230872;
			
			// aapt resource value: 0x7f080094
			public const int rlGenMsgContent = 2131230868;
			
			// aapt resource value: 0x7f080026
			public const int rlGenMsgListView = 2131230758;
			
			// aapt resource value: 0x7f080072
			public const int rlGeneralInfoBtn = 2131230834;
			
			// aapt resource value: 0x7f08005a
			public const int rlInfo = 2131230810;
			
			// aapt resource value: 0x7f080034
			public const int rlLeftMenuFeedback = 2131230772;
			
			// aapt resource value: 0x7f08002e
			public const int rlLeftMenuHome = 2131230766;
			
			// aapt resource value: 0x7f080031
			public const int rlLeftMenuMessages = 2131230769;
			
			// aapt resource value: 0x7f080032
			public const int rlLeftMenuProfile = 2131230770;
			
			// aapt resource value: 0x7f080033
			public const int rlLeftMenuSchoolInfo = 2131230771;
			
			// aapt resource value: 0x7f080035
			public const int rlLeftMenuSettings = 2131230773;
			
			// aapt resource value: 0x7f08007a
			public const int rlListing = 2131230842;
			
			// aapt resource value: 0x7f08006d
			public const int rlMMFOCContent = 2131230829;
			
			// aapt resource value: 0x7f08006a
			public const int rlMMFOCEventsBtn = 2131230826;
			
			// aapt resource value: 0x7f080064
			public const int rlMMFOCGenInfoBtn = 2131230820;
			
			// aapt resource value: 0x7f080067
			public const int rlMMFOCMessagesBtn = 2131230823;
			
			// aapt resource value: 0x7f080075
			public const int rlMessagesBtn = 2131230837;
			
			// aapt resource value: 0x7f08007f
			public const int rlMsgListView = 2131230847;
			
			// aapt resource value: 0x7f080090
			public const int rlPrivMsg = 2131230864;
			
			// aapt resource value: 0x7f08001a
			public const int rlSendFeedbackForm = 2131230746;
			
			// aapt resource value: 0x7f080000
			public const int tableLayout1 = 2131230720;
			
			// aapt resource value: 0x7f080007
			public const int tableRow1 = 2131230727;
			
			// aapt resource value: 0x7f08000b
			public const int tableRow3 = 2131230731;
			
			// aapt resource value: 0x7f08002d
			public const int textView1 = 2131230765;
			
			// aapt resource value: 0x7f080030
			public const int textView2 = 2131230768;
			
			// aapt resource value: 0x7f080040
			public const int textView3 = 2131230784;
			
			// aapt resource value: 0x7f080001
			public const int trComposeMsgAddresseeC = 2131230721;
			
			// aapt resource value: 0x7f080023
			public const int tvAppDesc = 2131230755;
			
			// aapt resource value: 0x7f080029
			public const int tvBriefDesc = 2131230761;
			
			// aapt resource value: 0x7f080002
			public const int tvComposeMsgAddresseeC = 2131230722;
			
			// aapt resource value: 0x7f080008
			public const int tvComposeMsgLayoutToLabel = 2131230728;
			
			// aapt resource value: 0x7f08000c
			public const int tvComposeMsgSubjectLabel = 2131230732;
			
			// aapt resource value: 0x7f080061
			public const int tvEmailLabel = 2131230817;
			
			// aapt resource value: 0x7f080015
			public const int tvEntranceLoadingLabel = 2131230741;
			
			// aapt resource value: 0x7f080019
			public const int tvEventsDate = 2131230745;
			
			// aapt resource value: 0x7f080097
			public const int tvEventsInfoEnd = 2131230871;
			
			// aapt resource value: 0x7f080093
			public const int tvEventsInfoEndLabel = 2131230867;
			
			// aapt resource value: 0x7f080096
			public const int tvEventsInfoStart = 2131230870;
			
			// aapt resource value: 0x7f080092
			public const int tvEventsInfoStartLabel = 2131230866;
			
			// aapt resource value: 0x7f080091
			public const int tvEventsInfoTitle = 2131230865;
			
			// aapt resource value: 0x7f080079
			public const int tvEventsLabel = 2131230841;
			
			// aapt resource value: 0x7f080018
			public const int tvEventsTitle = 2131230744;
			
			// aapt resource value: 0x7f080041
			public const int tvForgotPass = 2131230785;
			
			// aapt resource value: 0x7f08001d
			public const int tvFromLabel = 2131230749;
			
			// aapt resource value: 0x7f08009b
			public const int tvGenMsgCreatedLabel = 2131230875;
			
			// aapt resource value: 0x7f08009f
			public const int tvGenMsgCreatedOn = 2131230879;
			
			// aapt resource value: 0x7f08009d
			public const int tvGenMsgFrom = 2131230877;
			
			// aapt resource value: 0x7f080099
			public const int tvGenMsgFromLabel = 2131230873;
			
			// aapt resource value: 0x7f08009e
			public const int tvGenMsgTitle = 2131230878;
			
			// aapt resource value: 0x7f08009a
			public const int tvGenMsgTitleLabel = 2131230874;
			
			// aapt resource value: 0x7f080074
			public const int tvGeneralInfoLabel = 2131230836;
			
			// aapt resource value: 0x7f08005e
			public const int tvInfoAddress = 2131230814;
			
			// aapt resource value: 0x7f08005d
			public const int tvInfoAddressLabel = 2131230813;
			
			// aapt resource value: 0x7f08005c
			public const int tvInfoAppName = 2131230812;
			
			// aapt resource value: 0x7f080062
			public const int tvInfoEmail = 2131230818;
			
			// aapt resource value: 0x7f08005f
			public const int tvInfoTelLabel = 2131230815;
			
			// aapt resource value: 0x7f080060
			public const int tvInfoTelephone = 2131230816;
			
			// aapt resource value: 0x7f080039
			public const int tvLeftMenuListViewLabel = 2131230777;
			
			// aapt resource value: 0x7f08003b
			public const int tvLoginDesc = 2131230779;
			
			// aapt resource value: 0x7f08006c
			public const int tvMMFOCEventsLabel = 2131230828;
			
			// aapt resource value: 0x7f080066
			public const int tvMMFOCGenInfoLabel = 2131230822;
			
			// aapt resource value: 0x7f080069
			public const int tvMMFOCMessagesLabel = 2131230825;
			
			// aapt resource value: 0x7f080077
			public const int tvMessagesLabel = 2131230839;
			
			// aapt resource value: 0x7f080082
			public const int tvMsgSender = 2131230850;
			
			// aapt resource value: 0x7f080083
			public const int tvMsgSentDateTime = 2131230851;
			
			// aapt resource value: 0x7f080081
			public const int tvMsgTitle = 2131230849;
			
			// aapt resource value: 0x7f0800a2
			public const int tvPrivMsgCreatedLabel = 2131230882;
			
			// aapt resource value: 0x7f0800a6
			public const int tvPrivMsgCreatedOn = 2131230886;
			
			// aapt resource value: 0x7f0800a4
			public const int tvPrivMsgFrom = 2131230884;
			
			// aapt resource value: 0x7f0800a0
			public const int tvPrivMsgFromLabel = 2131230880;
			
			// aapt resource value: 0x7f0800a5
			public const int tvPrivMsgTitle = 2131230885;
			
			// aapt resource value: 0x7f0800a1
			public const int tvPrivMsgTitleLabel = 2131230881;
			
			// aapt resource value: 0x7f08002a
			public const int tvReadMore = 2131230762;
			
			// aapt resource value: 0x7f08003f
			public const int tvRegister = 2131230783;
			
			// aapt resource value: 0x7f08004c
			public const int tvResetPassDesc = 2131230796;
			
			// aapt resource value: 0x7f080028
			public const int tvSenderName = 2131230760;
			
			// aapt resource value: 0x7f08008c
			public const int tvSettingsName = 2131230860;
			
			// aapt resource value: 0x7f08008d
			public const int tvSettingsSubname = 2131230861;
			
			// aapt resource value: 0x7f08001b
			public const int tvToLabel = 2131230747;
			
			// aapt resource value: 0x7f080044
			public const int tvUserRegDesc = 2131230788;
			
			// aapt resource value: 0x7f080056
			public const int view1 = 2131230806;
			
			// aapt resource value: 0x7f080059
			public const int view2 = 2131230809;
			
			// aapt resource value: 0x7f080095
			public const int wvEventsInfoContent = 2131230869;
			
			// aapt resource value: 0x7f08009c
			public const int wvGenMsgContent = 2131230876;
			
			// aapt resource value: 0x7f0800a3
			public const int wvPrivMsgContent = 2131230883;
			
			// aapt resource value: 0x7f080084
			public const int wvProfileLayout = 2131230852;
			
			// aapt resource value: 0x7f080089
			public const int wvSchoolInfoLayout = 2131230857;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ComposeMsgAddresseeCell = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ComposeMsgAddresseeListView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ComposeMsgLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CustomMessageView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DrawerListItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int EntranceLoadingIndicator = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int EventsListView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int FeedbackFormLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int FeedbackLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int GeneralMsgListView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int LeftMenu = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int LeftMenuHeaderLayout = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int LeftMenuListView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int LeftMenuListViewCell = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Login = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int LoginRegLayout = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int LoginResetPass = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Main = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int MainContainer = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int MainMenuFOC = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int MainMenuLL = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int MessageLayout = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int MessageListView = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int ProfileLayout = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int ReadMoreLayout = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int ReadMorePMLayout = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int SchoolInfoLayout = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int SettingsLayout = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int SettingsListingView = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int SettingsResetPass = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int ViewEventsInfoContent = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int ViewGeneralMsgContent = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int ViewPrivateMsgContent = 2130903072;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f04000b
			public const int DrawerClose = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int DrawerOpen = 2130968586;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int app_name = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int app_subname = 2130968581;
			
			// aapt resource value: 0x7f04000d
			public const int app_subname_address = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int app_subname_address_label = 2130968588;
			
			// aapt resource value: 0x7f040011
			public const int app_subname_email = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int app_subname_email_label = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public const int app_subname_tel = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int app_subname_tel_label = 2130968590;
			
			// aapt resource value: 0x7f040014
			public const int btn_events = 2130968596;
			
			// aapt resource value: 0x7f040012
			public const int btn_generalinfo = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int btn_messages = 2130968595;
			
			// aapt resource value: 0x7f040007
			public const int button_login = 2130968583;
			
			// aapt resource value: 0x7f040037
			public const int composeMsg_From_Hint = 2130968631;
			
			// aapt resource value: 0x7f040036
			public const int composeMsg_From_Label = 2130968630;
			
			// aapt resource value: 0x7f040038
			public const int composeMsg_MessageContent_Hint = 2130968632;
			
			// aapt resource value: 0x7f04003a
			public const int composeMsg_Subject_Hint = 2130968634;
			
			// aapt resource value: 0x7f040039
			public const int composeMsg_Subject_Label = 2130968633;
			
			// aapt resource value: 0x7f040035
			public const int composeMsg_To_Hint = 2130968629;
			
			// aapt resource value: 0x7f040034
			public const int composeMsg_To_Label = 2130968628;
			
			// aapt resource value: 0x7f040024
			public const int ed_label_eventEnds = 2130968612;
			
			// aapt resource value: 0x7f040023
			public const int ed_label_eventStarts = 2130968611;
			
			// aapt resource value: 0x7f040025
			public const int ed_label_statusEvent = 2130968613;
			
			// aapt resource value: 0x7f04001f
			public const int eli_loadingText = 2130968607;
			
			// aapt resource value: 0x7f040033
			public const int event_btnReadMore = 2130968627;
			
			// aapt resource value: 0x7f040019
			public const int feedback_From_Label = 2130968601;
			
			// aapt resource value: 0x7f040018
			public const int feedback_To_Label = 2130968600;
			
			// aapt resource value: 0x7f040017
			public const int feedback_btn = 2130968599;
			
			// aapt resource value: 0x7f040016
			public const int feedback_desc = 2130968598;
			
			// aapt resource value: 0x7f040030
			public const int forgotPass_BtnResetPassSubmit = 2130968624;
			
			// aapt resource value: 0x7f04002c
			public const int forgotPass_Desc = 2130968620;
			
			// aapt resource value: 0x7f04002f
			public const int forgotPass_etUserRegConfirmPassPlaceholder = 2130968623;
			
			// aapt resource value: 0x7f04002d
			public const int forgotPass_etUserRegEmailPlaceholder = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int forgotPass_etUserRegPassPlaceholder = 2130968622;
			
			// aapt resource value: 0x7f040031
			public const int geninfo_btnReadmore = 2130968625;
			
			// aapt resource value: 0x7f04001e
			public const int gm_label_created = 2130968606;
			
			// aapt resource value: 0x7f04001c
			public const int gm_label_from = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int gm_label_title = 2130968605;
			
			// aapt resource value: 0x7f040003
			public const int hello = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040027
			public const int loginReg_BtnUserRegRegister = 2130968615;
			
			// aapt resource value: 0x7f040026
			public const int loginReg_Desc = 2130968614;
			
			// aapt resource value: 0x7f04002b
			public const int loginReg_etUserRegConfirmPassPlaceholder = 2130968619;
			
			// aapt resource value: 0x7f040029
			public const int loginReg_etUserRegEmailPlaceholder = 2130968617;
			
			// aapt resource value: 0x7f040028
			public const int loginReg_etUserRegNRICPlaceholder = 2130968616;
			
			// aapt resource value: 0x7f04002a
			public const int loginReg_etUserRegPassPlaceholder = 2130968618;
			
			// aapt resource value: 0x7f040032
			public const int msg_btnReadMore = 2130968626;
			
			// aapt resource value: 0x7f040015
			public const int pg_label = 2130968597;
			
			// aapt resource value: 0x7f040020
			public const int pmsg_label_from = 2130968608;
			
			// aapt resource value: 0x7f040022
			public const int pmsg_label_sent = 2130968610;
			
			// aapt resource value: 0x7f040021
			public const int pmsg_label_title = 2130968609;
			
			// aapt resource value: 0x7f04001b
			public const int readMoreText = 2130968603;
			
			// aapt resource value: 0x7f04003d
			public const int settingsResetPass_ConfirmPassHint = 2130968637;
			
			// aapt resource value: 0x7f04003b
			public const int settingsResetPass_Desc = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int settingsResetPass_NewPassHint = 2130968636;
			
			// aapt resource value: 0x7f04001a
			public const int textTest = 2130968602;
			
			// aapt resource value: 0x7f040009
			public const int textview_forgotpass = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int textview_login = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int textview_register = 2130968584;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070002
			public const int ActionBar_Solid_Schoolapp = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int ActionBar_Transparent_Schoolapp = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int ActionBarTabStyle_Schoolapp = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int ActionButton_CloseMode_Schoolapp = 2131165193;
			
			// aapt resource value: 0x7f070005
			public const int DropDownListView_Schoolapp = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int DropDownNav_Schoolapp = 2131165191;
			
			// aapt resource value: 0x7f070011
			public const int Mono_Android_Theme_Splash = 2131165201;
			
			// aapt resource value: 0x7f070004
			public const int PopupMenu_Schoolapp = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int ProgressBar_Schoolapp = 2131165192;
			
			// aapt resource value: 0x7f07000f
			public const int Theme_FeedbackForm = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int Theme_ForDrawer = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int Theme_HoloLight_RemovedTitle = 2131165200;
			
			// aapt resource value: 0x7f07000c
			public const int Theme_LoginScreen = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int Theme_MainMenu = 2131165197;
			
			// aapt resource value: 0x7f070000
			public const int Theme_Schoolapp = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int Theme_Schoolapp_NoNativeTitleBar = 2131165185;
			
			// aapt resource value: 0x7f07000a
			public const int Theme_Schoolapp_Widget = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int Theme_SplashScreen = 2131165195;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
